name: CloudScope CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Security scanning and code quality
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Check for Python files
      id: check-python
      run: |
        if find . -name "*.py" -not -path "./.git/*" | head -1 | grep -q .; then
          echo "has-python=true" >> $GITHUB_OUTPUT
        else
          echo "has-python=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Install dependencies
      if: steps.check-python.outputs.has-python == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety semgrep
    
    - name: Run Bandit security scanner
      if: steps.check-python.outputs.has-python == 'true'
      run: |
        bandit -r . -f json -o bandit-report.json || true
    
    - name: Run Safety vulnerability scanner
      if: steps.check-python.outputs.has-python == 'true' && hashFiles('requirements.txt') != ''
      run: |
        safety check --json --output safety-report.json || true
    
    - name: Run Semgrep security scanner
      if: steps.check-python.outputs.has-python == 'true'
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      run: |
        semgrep --config=auto --json --output=semgrep-report.json . || true
    
    - name: Skip security scans
      if: steps.check-python.outputs.has-python == 'false'
      run: echo "No Python files found - skipping security scans (POC repository)"
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          semgrep-report.json

  # Code quality and linting
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Check for requirements-dev.txt
      id: check-dev-deps
      run: |
        if [ -f "requirements-dev.txt" ]; then
          echo "has-dev-deps=true" >> $GITHUB_OUTPUT
        else
          echo "has-dev-deps=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Install dependencies
      if: steps.check-dev-deps.outputs.has-dev-deps == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run Black code formatter check
      if: steps.check-dev-deps.outputs.has-dev-deps == 'true'
      run: |
        black --check --diff . || echo "Black not configured - skipping"
      continue-on-error: true
    
    - name: Run isort import sorter check
      if: steps.check-dev-deps.outputs.has-dev-deps == 'true'
      run: |
        isort --check-only --diff . || echo "isort not configured - skipping"
      continue-on-error: true
    
    - name: Run flake8 linter
      if: steps.check-dev-deps.outputs.has-dev-deps == 'true'
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "flake8 not configured - skipping"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || true
      continue-on-error: true
    
    - name: Run mypy type checker
      if: steps.check-dev-deps.outputs.has-dev-deps == 'true' && hashFiles('core/**/*.py') != ''
      run: |
        mypy core/ --ignore-missing-imports --no-strict-optional || echo "mypy not configured - skipping"
      continue-on-error: true
    
    - name: Skip code quality checks
      if: steps.check-dev-deps.outputs.has-dev-deps == 'false'
      run: echo "No requirements-dev.txt found - skipping code quality checks (POC repository)"

  # PowerShell script testing
  powershell-tests:
    name: PowerShell Tests
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install PowerShell modules
      shell: powershell
      run: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module -Name Pester -Force -SkipPublisherCheck
        Install-Module -Name PSScriptAnalyzer -Force
    
    - name: Check for PowerShell files
      shell: powershell
      id: check-ps
      run: |
        $psFiles = Get-ChildItem -Path . -Recurse -Include *.ps1,*.psm1,*.psd1 -ErrorAction SilentlyContinue
        if ($psFiles.Count -gt 0) {
          echo "has-powershell=true" >> $env:GITHUB_OUTPUT
        } else {
          echo "has-powershell=false" >> $env:GITHUB_OUTPUT
        }
    
    - name: Run PowerShell Script Analyzer
      if: steps.check-ps.outputs.has-powershell == 'true'
      shell: powershell
      run: |
        $results = Invoke-ScriptAnalyzer -Path ./powershell/ -Recurse -ReportSummary -ErrorAction SilentlyContinue
        if ($results.Count -gt 0) {
          $results | Format-Table
          Write-Warning "PSScriptAnalyzer found $($results.Count) issues"
        }
      continue-on-error: true
    
    - name: Skip PowerShell analysis
      if: steps.check-ps.outputs.has-powershell == 'false'
      shell: powershell
      run: Write-Host "No PowerShell files found - skipping analysis (POC repository)"
    
    - name: Run PowerShell tests
      if: steps.check-ps.outputs.has-powershell == 'true'
      shell: powershell
      run: |
        # Run Pester tests if they exist
        if (Test-Path "./tests/powershell") {
          Invoke-Pester -Path "./tests/powershell" -OutputFormat NUnitXml -OutputFile "powershell-test-results.xml"
        } else {
          Write-Host "No PowerShell tests found - skipping"
        }
      continue-on-error: true

  # Python unit tests
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    services:
      memgraph:
        image: memgraph/memgraph:latest
        ports:
          - 7687:7687
        options: >-
          --health-cmd "echo 'MATCH (n) RETURN count(n);' | mgconsole"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Wait for services
      run: |
        sleep 30
    
    - name: Run pytest
      env:
        MEMGRAPH_HOST: localhost
        MEMGRAPH_PORT: 7687
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        JWT_SECRET_KEY: test-secret-key-for-ci
      run: |
        pytest tests/ -v --cov=core --cov-report=xml --cov-report=html
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  # Integration tests
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [python-tests]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Start CloudScope services
      run: |
        docker-compose -f docker-compose.test.yml up -d
        sleep 60  # Wait for services to be ready
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --timeout=300
    
    - name: Check service health
      run: |
        curl -f http://localhost:8000/health || exit 1
    
    - name: Collect logs
      if: failure()
      run: |
        docker-compose -f docker-compose.test.yml logs
    
    - name: Cleanup
      if: always()
      run: |
        docker-compose -f docker-compose.test.yml down -v

  # Build and push Docker image
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [security-scan, code-quality, python-tests]
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          VCS_REF=${{ github.sha }}
          VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Performance testing
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust requests
    
    - name: Start CloudScope services
      run: |
        docker-compose up -d
        sleep 60
    
    - name: Run performance tests
      run: |
        # Run basic load test
        locust -f tests/performance/locustfile.py --headless -u 10 -r 2 -t 60s --host http://localhost:8000
    
    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v

  # Deploy to staging (only on main branch)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build-and-push, integration-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add your staging deployment logic here
        # Example: kubectl apply -f k8s/staging/
    
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        # Add smoke test logic here

  # Create release
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog from git commits
        CHANGELOG=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD)
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Get next version
      id: version
      run: |
        # Calculate next version (simplified)
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        NEXT_VERSION=$(echo $LAST_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: CloudScope ${{ steps.version.outputs.version }}
        body: |
          ## Changes in this Release
          ${{ steps.changelog.outputs.changelog }}
          
          ## Docker Images
          - `ghcr.io/geeksikhsecurity/cloudscope:${{ steps.version.outputs.version }}`
          - `ghcr.io/geeksikhsecurity/cloudscope:latest`
          
          ## Installation
          ```bash
          docker pull ghcr.io/geeksikhsecurity/cloudscope:${{ steps.version.outputs.version }}
          ```
        draft: false
        prerelease: false

  # Notify on failure
  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [security-scan, code-quality, python-tests, integration-tests, build-and-push]
    if: failure()
    
    steps:
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#cloudscope-alerts'
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
